import {
  QUERIES_GET_POSTS,
  QUERIES_GET_POSTS_BY_AUTHOR,
  QUERIES_GET_POSTS_BY_CATEGORY,
  QUERIES_GET_POSTS_BY_SLUG,
  QUERIES_GET_POSTS_BY_TAG,
  QUERIES_GET_POSTS_BY_TITLE,
} from '../graphql/queries';

export const paginationQueries = {
  allPosts: QUERIES_GET_POSTS,
  author: QUERIES_GET_POSTS_BY_AUTHOR,
  category: QUERIES_GET_POSTS_BY_CATEGORY,
  tag: QUERIES_GET_POSTS_BY_TAG,
  title: QUERIES_GET_POSTS_BY_TITLE,
  slug: QUERIES_GET_POSTS_BY_SLUG,
};
